### PR TITLE
upgrade to jetty 12

### PR DESCRIPTION
**Pull request by andrew-tram**
upgrade to jetty 12

https://github.com/eclipse-jgit/jgit/issues/41

Thank you for contributing to JGit!

JGit uses [GerritHub](https://eclipse.gerrithub.io) for code changes and review, therefore **pull requests in this repository cannot be merged**.

Please make sure you have read the section on [contributing patches](https://github.com/eclipse-egit/egit/wiki/Contributor-Guide#contributing-patches) of the [Contributor Guide](https://github.com/eclipse-egit/egit/wiki/Contributor-Guide).

### CODE REVIEW

**Comment by andrew-tram** [comment]
After reading through the contributor guide, I'm still unable to submit changes for review. Unfortunately, I won't be able to commit any more time to this and will leave it as it is.

**Comment by andrew-tram** [comment]
I was wondering if anybody had thoughts on this.

**Comment by davido** [comment]
> Unfortunately, I won't be able to commit any more time to this and will leave it as it is.

Can you provide more insight, what exactly doesn't work for you, or mention the error message during the push?

**Comment by davido** [comment]
@lucamilanesio I tried to import this PR using github-plugin but got an error during the import. Can you clarify, if the import workflow of PR is supported for JGit project?

**Comment by davido** [comment]
I cherry-picked the PR and uploaded it to Gerrithub:

https://review.gerrithub.io/c/eclipse-jgit/jgit/+/1194275

**Comment by msohn** [comment]
Update to jetty 12 was submitted on the next branch
https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1194291
and will be merged to master soon
https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1195683

**Pull request closed without merging**
